-- ------------------------------------------------------------
-- 1.1 CLIENTES: almacena personas que compran
-- PK: id_cliente (numérico autogenerado)
-- Restricciones: nombre obligatorio; email único
-- ------------------------------------------------------------
CREATE TABLE clientes (
  id_cliente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- PK autoincremental
  nombre     VARCHAR2(100) NOT NULL,                              -- NOT NULL: obliga a informar
  email      VARCHAR2(150) UNIQUE,                                -- UNIQUE: no se repiten emails
  creado_en  DATE DEFAULT SYSDATE                                 -- valor por defecto: fecha actual
);

-- ------------------------------------------------------------
-- 1.2 PRODUCTOS: catálogo de productos
-- PK: id_producto
-- Restricciones: precio no negativo (CHECK)
-- ------------------------------------------------------------
CREATE TABLE productos (
  id_producto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      VARCHAR2(120) NOT NULL,
  precio      NUMBER(10,2)  NOT NULL CHECK (precio >= 0)
);

-- ------------------------------------------------------------
-- 1.3 PEDIDOS: encabezado del pedido (uno por cliente y fecha)
-- Relación 1:N con clientes (un cliente tiene muchos pedidos)
-- ------------------------------------------------------------
CREATE TABLE pedidos (
  id_pedido   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_cliente  NUMBER NOT NULL,
  fecha_ped   DATE DEFAULT SYSDATE,
  CONSTRAINT fk_pedidos_cliente
    FOREIGN KEY (id_cliente) REFERENCES clientes(id_cliente)      -- FK: asegura que el cliente exista
);

-- ------------------------------------------------------------
-- 1.4 PEDIDOS_ITEMS: detalle del pedido (N:M entre pedidos y productos)
-- Relación N:M: un pedido tiene muchos productos y un producto aparece en muchos pedidos
-- Implementado con tabla intermedia (pedido_item)
-- ------------------------------------------------------------
CREATE TABLE pedidos_items (
  id_item     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pedido   NUMBER NOT NULL,
  id_producto NUMBER NOT NULL,
  cantidad    NUMBER(10) NOT NULL CHECK (cantidad > 0),
  total_linea NUMBER(12,2),                                       -- total calculado (cantidad * precio)
  CONSTRAINT fk_items_pedido   FOREIGN KEY (id_pedido)   REFERENCES pedidos(id_pedido),
  CONSTRAINT fk_items_producto FOREIGN KEY (id_producto) REFERENCES productos(id_producto)
);

-- (Opcional) Trigger para calcular el total de la línea automáticamente
CREATE OR REPLACE TRIGGER trg_items_total
BEFORE INSERT OR UPDATE OF cantidad, id_producto ON pedidos_items
FOR EACH ROW
DECLARE
  v_precio productos.precio%TYPE;
BEGIN
  SELECT precio INTO v_precio FROM productos WHERE id_producto = :NEW.id_producto;
  :NEW.total_linea := :NEW.cantidad * v_precio;
END;
/
